# Generated by Django 5.1.7 on 2025-04-21 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0003_convo_reply_delete_post"),
        ("users", "0002_alter_profile_community"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="community",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="communities.community",
            ),
        ),
    ]
