# Generated by Django 5.1.6 on 2025-04-24 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profile_community"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
    ]
