# Generated by Django 5.1.7 on 2025-04-21 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0003_convo_reply_delete_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="convo",
            name="title",
        ),
    ]
