# Generated by Django 5.1.7 on 2025-04-21 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0005_convo_title_alter_reply_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reply",
            options={"verbose_name_plural": "Replies"},
        ),
        migrations.RemoveField(
            model_name="reply",
            name="title",
        ),
        migrations.AddField(
            model_name="reply",
            name="convo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="communities.convo",
            ),
        ),
    ]
