# Generated by Django 5.1.7 on 2025-04-21 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0006_alter_reply_options_remove_reply_title_reply_convo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="convo",
            old_name="commmunity",
            new_name="community",
        ),
    ]
