# Generated by Django 5.1.7 on 2025-04-21 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0007_rename_commmunity_convo_community"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reply",
            old_name="creator",
            new_name="profile",
        ),
    ]
