# Generated by Django 5.1.7 on 2025-04-21 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0008_rename_creator_reply_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="convo",
            name="community",
        ),
        migrations.AddField(
            model_name="circle",
            name="convo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="communities.convo",
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="convo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="communities.convo",
            ),
        ),
    ]
