# Generated by Django 5.1.7 on 2025-04-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0009_remove_convo_community_circle_convo_community_convo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="circle",
            name="convo",
        ),
        migrations.RemoveField(
            model_name="community",
            name="convo",
        ),
        migrations.AddField(
            model_name="circle",
            name="convo",
            field=models.ManyToManyField(to="communities.convo"),
        ),
        migrations.AddField(
            model_name="community",
            name="convo",
            field=models.ManyToManyField(to="communities.convo"),
        ),
    ]
