# Generated by Django 5.1.7 on 2025-04-21 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0010_remove_circle_convo_remove_community_convo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="circle",
            name="convo",
        ),
        migrations.RemoveField(
            model_name="community",
            name="convo",
        ),
        migrations.AddField(
            model_name="convo",
            name="circle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="communities.circle",
            ),
        ),
        migrations.AddField(
            model_name="convo",
            name="community",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="communities.community",
            ),
        ),
    ]
